import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {owner,member,p,db,call} from './server.mjs';
const browser=await chromium.launch({headless:true,channel:'chromium'}),base='http://127.0.0.1:5174';
async function login(page,email){await page.goto(base);await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('Testing123!');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Integration',exact:true}).waitFor();await page.getByRole('heading',{name:'Concurrent left',exact:true}).waitFor();}
async function create(page,title){await page.getByRole('button',{name:'New task',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill(title);await page.getByRole('button',{name:'Save task',exact:true}).click();}
async function saved(page){await page.locator('.save-status').getByText('Saved',{exact:true}).waitFor();}
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await login(page,'owner@example.com');await create(page,'Remote persisted');await saved(page);await page.reload();await page.getByRole('heading',{name:'Remote persisted',exact:true}).waitFor();
 let fail=true;await page.route('**/europe-west3/projectCommand',async route=>{if(fail){fail=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{status:'UNAVAILABLE',message:'Simulated disconnected request'}})});}else await route.continue();});
 await create(page,'Network retry task');await page.getByText('Save failed',{exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:'Network retry task',exact:true}).count(),0);await page.getByRole('button',{name:'Retry',exact:true}).click();await saved(page);await page.getByRole('heading',{name:'Network retry task',exact:true}).waitFor();await page.unroute('**/europe-west3/projectCommand');
 // Lose only the response after the server committed: retry must use the same receipt.
 let lose=true;await page.route('**/europe-west3/projectCommand',async route=>{if(lose){lose=false;await route.fetch();await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{status:'UNAVAILABLE',message:'Simulated lost acknowledgement'}})});}else await route.continue();});
 await create(page,'Acknowledgement retry');await page.getByText('Save failed',{exact:true}).waitFor();await page.getByRole('button',{name:'Retry',exact:true}).click();await saved(page);assert.equal((await db.collection(`accounts/${owner.uid}/projects/${p.id}/tasks`).where('title','==','Acknowledgement retry').get()).size,1);await page.unroute('**/europe-west3/projectCommand');
 let first=true;await page.route('**/europe-west3/projectCommand',async route=>{if(first){first=false;await new Promise(r=>setTimeout(r,800));await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{status:'UNAVAILABLE',message:'Simulated queued failure'}})});}else await route.continue();});await create(page,'Queue first');await create(page,'Queue dependent');await page.getByText('Save failed',{exact:true}).waitFor();await page.getByRole('button',{name:'Retry',exact:true}).click();await saved(page);assert.equal((await db.collection(`accounts/${owner.uid}/projects/${p.id}/tasks`).where('title','==','Queue first').get()).size,1);assert.equal((await db.collection(`accounts/${owner.uid}/projects/${p.id}/tasks`).where('title','==','Queue dependent').get()).size,0);await page.unroute('**/europe-west3/projectCommand');
 await page.context().setOffline(true);await create(page,'Offline rollback');await page.getByText('Save failed',{exact:true}).waitFor();await page.context().setOffline(false);await page.getByRole('button',{name:'Retry',exact:true}).click();await saved(page);await page.getByRole('heading',{name:'Offline rollback',exact:true}).waitFor();
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export project',exact:true}).click();const downloaded=await downloadEvent;const backup=JSON.parse(await readFile(await downloaded.path(),'utf8'));assert.ok(backup.tasks.some(t=>t.title==='Remote persisted'));assert.ok(backup.comments.some(c=>c.content==='private discussion'));
 const secondTab=await browser.newPage();await login(secondTab,'owner@example.com');await page.getByRole('button').filter({has:page.getByRole('heading',{name:'Remote persisted',exact:true})}).click();await page.getByLabel('Title',{exact:true}).fill('Stale modal overwrite');await secondTab.getByRole('button').filter({has:secondTab.getByRole('heading',{name:'Remote persisted',exact:true})}).click();await secondTab.getByLabel('Title',{exact:true}).fill('Remote updated in second tab');await secondTab.getByRole('button',{name:'Save task',exact:true}).click();await saved(secondTab);await page.getByRole('heading',{name:'Remote updated in second tab',exact:true}).waitFor();await page.getByRole('button',{name:'Save task',exact:true}).click();await page.getByText('Task changed while editing. Close and reopen it before saving.',{exact:true}).waitFor();assert.equal((await db.collection(`accounts/${owner.uid}/projects/${p.id}/tasks`).where('title','==','Stale modal overwrite').get()).size,0);await page.getByRole('button',{name:'Close',exact:true}).click();await secondTab.close();
 const colleague=await browser.newPage();await login(colleague,'member@example.com');assert.equal(await colleague.getByRole('button',{name:'New task',exact:true}).count(),0);await colleague.getByRole('button').filter({has:colleague.getByRole('heading',{name:'Concurrent left',exact:true})}).click();assert.equal(await colleague.getByLabel('Title',{exact:true}).isDisabled(),true);await colleague.getByRole('button',{name:'Close',exact:true}).click();
 const link=await call('shareProject',{projectId:p.id,action:'rotate'},owner),publicPage=await browser.newPage({viewport:{width:390,height:844}});await publicPage.goto(base+'/#portal='+link.url.split('#portal=')[1]);await publicPage.getByRole('heading',{name:'Integration',exact:true}).waitFor();assert.equal(await publicPage.getByText('private discussion',{exact:true}).count(),0);assert.equal(await publicPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await publicPage.getByRole('button',{name:'Project comments',exact:true}).click();await publicPage.getByLabel('Your name',{exact:true}).fill('Browser client');await publicPage.getByLabel('Comment',{exact:true}).fill('Client browser comment');await publicPage.getByRole('button',{name:'Post comment',exact:true}).click();await publicPage.getByText('Comment posted.',{exact:true}).waitFor();await publicPage.keyboard.press('Escape');assert.equal(await publicPage.getByRole('dialog').count(),0);await publicPage.screenshot({path:'test-results/server-portal-mobile.png'});
 await call('shareProject',{projectId:p.id,action:'revoke'},owner);await publicPage.reload();await publicPage.getByRole('heading',{name:'Client link unavailable',exact:true}).waitFor();
 await page.screenshot({path:'test-results/server-workspace.png'});assert.deepEqual(errors,[]);console.log('Emulator browser checks passed: auth, cloud persistence, failed request rollback/retry, lost acknowledgement idempotency, complete export, member permissions, mobile guest comments, focus/Escape and revoked link.');
}finally{await browser.close();}
