import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,channel:'chromium'});
try {
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173');
 await page.getByRole('button',{name:'Open local demo',exact:true}).click();
 await page.getByRole('heading',{name:'Website launch',exact:true}).waitFor();
 await page.getByRole('button',{name:'New task',exact:true}).click();
 await page.getByLabel('Title',{exact:true}).fill('Browser verified task');
 await page.getByRole('button',{name:'Save task',exact:true}).click();
 await page.getByRole('button').filter({hasText:'Browser verified task'}).waitFor();
 await page.reload();
 await page.getByRole('button',{name:'Open local demo',exact:true}).click();
 await page.getByRole('button').filter({hasText:'Browser verified task'}).waitFor();
 await page.getByRole('button',{name:'Demo controls',exact:true}).click();
 await page.getByLabel('Preview as').selectOption({label:'Alex Morgan (Member)'});
 await page.getByRole('button',{name:'Close',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'New task',exact:true}).count(),0);
 await page.getByRole('button').filter({hasText:'Browser verified task'}).click();
 assert.equal(await page.getByLabel('Title',{exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Suggest change',exact:true}).click();
 await page.getByLabel('Title',{exact:true}).fill('Member suggestion');
 await page.getByRole('button',{name:'Submit suggestion',exact:true}).click();
 await page.getByRole('button',{name:'Demo controls',exact:true}).click();
 await page.getByLabel('Preview as').selectOption('owner');
 await page.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Suggestions',exact:true}).click();
 await page.getByRole('button',{name:'Accept',exact:true}).click();
 await page.getByRole('button',{name:'Board',exact:true}).click();
 await page.getByRole('button').filter({hasText:'Member suggestion'}).waitFor();
 await page.getByRole('button',{name:'New task',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Recovered draft');await page.getByLabel('Visible to client',{exact:true}).uncheck();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'New task',exact:true}).click();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Recovered draft');assert.equal(await page.getByLabel('Visible to client',{exact:true}).isChecked(),false);await page.getByRole('button',{name:'Save task',exact:true}).click();
 await page.getByRole('button').filter({has:page.getByRole('heading',{name:'Recovered draft',exact:true})}).click();await page.getByRole('button',{name:'Delete task',exact:true}).click();await page.getByRole('button',{name:'Trash',exact:true}).click();await page.getByRole('button',{name:'Restore Recovered draft',exact:true}).click();await page.getByRole('button',{name:'Board',exact:true}).click();await page.getByRole('heading',{name:'Recovered draft',exact:true}).waitFor();
 const handle=page.getByRole('button',{name:'Move Member suggestion',exact:true});await handle.focus();await page.keyboard.press('Space');await page.keyboard.press('ArrowRight');await page.keyboard.press('Space');await page.getByRole('button',{name:'Undo move',exact:true}).waitFor();await page.getByRole('button',{name:'Undo move',exact:true}).click();
 await page.screenshot({path:'test-results/workspace-desktop.png'});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button').filter({has:page.getByRole('heading',{name:'Member suggestion',exact:true})}).click();await page.screenshot({path:'test-results/task-modal-mobile.png'});await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});await page.setViewportSize({width:1440,height:900});
 await page.getByRole('button',{name:'Client preview',exact:true}).click();
 assert.equal(await page.getByRole('button').filter({hasText:'Review content structure'}).count(),0);
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 assert.deepEqual(errors,[]);
 console.log('Browser checks passed: persistence, permissions, suggestions, draft/checkbox recovery, trash/restore, keyboard drag/undo, mobile modal, client visibility and overflow.');
} finally {await browser.close();}
