import {readFile} from 'node:fs/promises';
import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {doc,getDoc,setDoc,writeBatch,connectFirestoreEmulator,getFirestore,terminate} from 'firebase/firestore';
import {initializeApp,deleteApp} from 'firebase/app';
import {getAuth,connectAuthEmulator,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut} from 'firebase/auth';
import assert from 'node:assert/strict';
import {makeProject} from '../src/domain.ts';

const env=await initializeTestEnvironment({projectId:'demo-clientflow',firestore:{rules:await readFile('firestore.rules','utf8')}});
try {
 await env.clearFirestore();
 const owner=env.authenticatedContext('owner-user').firestore();
 const stranger=env.authenticatedContext('other-user').firestore();
 const anonymous=env.unauthenticatedContext().firestore();
 const path='accounts/owner-user';
 const first=makeProject('First project');
 const account={plan:'free',revision:1,activeProjectId:first.id,notifications:[]};
 const batch=writeBatch(owner);
 batch.set(doc(owner,path),account);
 batch.set(doc(owner,path,'projects',first.id),first);
 await assertSucceeds(batch.commit());
 await assertSucceeds(getDoc(doc(owner,path,'projects',first.id)));
 await assertFails(getDoc(doc(stranger,path,'projects',first.id)));
 await assertFails(getDoc(doc(anonymous,path,'projects',first.id)));
 await assertFails(setDoc(doc(stranger,path),{...account,revision:2}));
 await assertFails(setDoc(doc(owner,path),{...account,plan:'pro',revision:2}));
 const second=makeProject('Second project');
 const extra=writeBatch(owner);
 extra.set(doc(owner,path),{...account,revision:2,activeProjectId:second.id});
 extra.set(doc(owner,path,'projects',second.id),second);
 await assertFails(extra.commit());
 const closed={...first,status:'completed'};
 const complete=writeBatch(owner);
 complete.set(doc(owner,path),{...account,revision:2,activeProjectId:''});
 complete.set(doc(owner,path,'projects',first.id),closed);
 await assertSucceeds(complete.commit());
 const editHistory=writeBatch(owner);
 editHistory.set(doc(owner,path),{...account,revision:3,activeProjectId:''});
 editHistory.set(doc(owner,path,'projects',first.id),{...closed,name:'Changed history'});
 await assertFails(editHistory.commit());
 const next=writeBatch(owner);
 next.set(doc(owner,path),{...account,revision:3,activeProjectId:second.id});
 next.set(doc(owner,path,'projects',second.id),second);
 await assertSucceeds(next.commit());
 const reactivation=writeBatch(owner);
 reactivation.set(doc(owner,path),{...account,revision:4,activeProjectId:first.id});
 reactivation.set(doc(owner,path,'projects',first.id),first);
 await assertFails(reactivation.commit());
 await assertFails(setDoc(doc(owner,path,'projects',second.id),{...second,name:'Without revision'}));
 await env.withSecurityRulesDisabled(async context=>{const db=context.firestore();await setDoc(doc(db,path),{...account,schema:3,activeProjectId:second.id});await setDoc(doc(db,path,'projects',second.id),{...second,schema:3});await setDoc(doc(db,path,'projects',second.id,'tasks','private-task'),{id:'private-task',title:'Private'});await setDoc(doc(db,'users','other-user','memberships',`owner-user_${second.id}`),{owner:'owner-user',projectId:second.id});await setDoc(doc(db,'publicProjects','private-projection'),{name:'Protected'});await setDoc(doc(db,'portalTokens','secret-hash'),{owner:'owner-user'});});
 await assertSucceeds(getDoc(doc(stranger,path,'projects',second.id,'tasks','private-task')));
 await assertFails(setDoc(doc(stranger,path,'projects',second.id,'tasks','private-task'),{title:'Forged'}));
 await assertFails(setDoc(doc(owner,path),{...account,revision:2}));
 await assertFails(setDoc(doc(owner,path,'projects',second.id),second));
 await assertFails(getDoc(doc(anonymous,'publicProjects','private-projection')));
 await assertFails(getDoc(doc(owner,'portalTokens','secret-hash')));
 await assertFails(setDoc(doc(stranger,'users','other-user','memberships','forged'),{owner:'owner-user',projectId:first.id}));
 await env.withSecurityRulesDisabled(async context=>{const {deleteDoc}=await import('firebase/firestore');await deleteDoc(doc(context.firestore(),'users','other-user','memberships',`owner-user_${second.id}`));});
 await assertFails(getDoc(doc(stranger,path,'projects',second.id,'tasks','private-task')));
 const app=initializeApp({projectId:'demo-clientflow',apiKey:'fake-test-key',authDomain:'demo-clientflow.firebaseapp.com'},'auth-rule-integration');
 const realAuth=getAuth(app),realDb=getFirestore(app);
 connectAuthEmulator(realAuth,'http://127.0.0.1:9099',{disableWarnings:true});
 connectFirestoreEmulator(realDb,'127.0.0.1',8080);
 try {
  const registered=await createUserWithEmailAndPassword(realAuth,'owner@example.test','test-password-123');
  const userId=registered.user.uid;
  const privateAccount=doc(realDb,'accounts',userId);
  await assertSucceeds(setDoc(privateAccount,{plan:'free',revision:1,activeProjectId:'',notifications:[]}));
  await signOut(realAuth);
  await assertFails(getDoc(privateAccount));
  const login=await signInWithEmailAndPassword(realAuth,'owner@example.test','test-password-123');
  assert.equal(login.user.uid,userId);
  await assertSucceeds(getDoc(privateAccount));
  console.log('Authentication integration passed: registration, sign-out denial and email/password sign-in.');
 } finally {await signOut(realAuth);await terminate(realDb);await deleteApp(app);}
 console.log('Firestore rules passed: owner isolation, anonymous denial, Pro escalation denial, active slot enforcement, read-only history and slot reuse.');
} finally {await env.cleanup();}
