import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import {makeProject,templateProject} from '../src/domain.ts';
import {projectPatch} from '../src/patches.ts';
import {processEmailItem} from '../functions/src/email.ts';
const require=createRequire(new URL('../functions/package.json',import.meta.url));
const {initializeApp}=require('firebase-admin/app'),{getFirestore}=require('firebase-admin/firestore'),{getAuth}=require('firebase-admin/auth');
initializeApp({projectId:'demo-clientflow'});const db=getFirestore(),auth=getAuth();
const root='http://127.0.0.1:5001/demo-clientflow/europe-west3/';
async function user(email){const password='Testing123!';const signup=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signUp?key=fake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});const account=await signup.json();assert.ok(account.localId);await auth.updateUser(account.localId,{emailVerified:true,displayName:email.split('@')[0]});const response=await fetch('http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=fake',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});return {uid:account.localId,token:(await response.json()).idToken};}
async function call(name,data,user,ok=true){const response=await fetch(root+name,{method:'POST',headers:{'Content-Type':'application/json',...(user?{Authorization:'Bearer '+user.token}:{})},body:JSON.stringify({data})}),result=await response.json();if(ok)assert.ok(!result.error,JSON.stringify(result));else assert.ok(result.error,'Expected denial');return result.result;}
const owner=await user('owner@example.com'),member=await user('member@example.com'),outsider=await user('outsider@example.com');
assert.ok(process.env.FIREBASE_AUTH_EMULATOR_HOST,'These tests must never run against production.');
let p=templateProject('Integration','website');p.members[0]={id:'owner',name:'owner',email:'owner@example.com',uid:owner.uid,collaborating:true};
const payload={owner:owner.uid,projectId:p.id,requestId:randomUUID(),patch:projectPatch(undefined,p)};
await call('projectCommand',payload,owner);await call('projectCommand',payload,owner);assert.equal((await db.collection(`accounts/${owner.uid}/projects/${p.id}/tasks`).get()).size,4);
await call('projectCommand',{owner:owner.uid,projectId:makeProject('Denied').id,requestId:randomUUID(),patch:projectPatch(undefined,makeProject('Extra'))},owner,false);
const ref=db.doc(`accounts/${owner.uid}/projects/${p.id}`);p={...(await ref.get()).data(),tasks:(await ref.collection('tasks').get()).docs.map(d=>d.data()),comments:[],suggestions:[]};
const changed=structuredClone(p);changed.tasks[0].title='Updated';changed.tasks[0].revision++;
await call('projectCommand',{owner:owner.uid,projectId:p.id,requestId:randomUUID(),patch:projectPatch(p,changed)},owner);
await call('projectCommand',{owner:owner.uid,projectId:p.id,requestId:randomUUID(),patch:projectPatch(p,changed)},owner,false);
await call('projectCommand',{owner:owner.uid,projectId:p.id,requestId:randomUUID(),patch:projectPatch(changed,changed)},outsider,false);
const invitation=await call('inviteMember',{projectId:p.id,email:'member@example.com'},owner),token=invitation.url.split('#invite=')[1];
await call('acceptInvitation',{token},outsider,false);await call('acceptInvitation',{token},member);assert.ok((await db.doc(`users/${member.uid}/memberships/${owner.uid}_${p.id}`).get()).exists);
p={...(await ref.get()).data(),tasks:(await ref.collection('tasks').get()).docs.map(d=>d.data()),comments:[],suggestions:[]};
const denied=structuredClone(p);denied.tasks[0].title='Unauthorized';denied.tasks[0].revision++;await call('projectCommand',{owner:owner.uid,projectId:p.id,requestId:randomUUID(),patch:projectPatch(p,denied)},member,false);
const commenting=structuredClone(p);commenting.comments.push({id:randomUUID(),task:'',author:'spoof',audience:'internal',content:'private discussion',created:'now'});await call('projectCommand',{owner:owner.uid,projectId:p.id,requestId:randomUUID(),patch:projectPatch(p,commenting)},member);
const share=await call('shareProject',{projectId:p.id,action:'rotate'},owner),portalToken=share.url.split('#portal=')[1];
async function portal(body,ok=true){const response=await fetch(root+'clientPortal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:portalToken,session:'integration',...body})});const result=await response.json();assert.equal(response.ok,ok,JSON.stringify(result));return result;}
const publicValue=await portal({});assert.ok(!JSON.stringify(publicValue).includes('private discussion'));assert.ok(!JSON.stringify(publicValue).includes('description'));
await portal({action:'comment',name:'Client',content:'Please review',task:'',requestId:randomUUID()});
await portal({action:'comment',name:'Client',content:'https://spam.example',task:'',requestId:randomUUID()},false);
await call('shareProject',{projectId:p.id,action:'revoke'},owner);await portal({},false);
const legacy=makeProject('Legacy');const example=templateProject('Old','website').tasks[0];legacy.tasks=Array.from({length:1001},(_,i)=>({...example,id:randomUUID(),number:i+1,rank:(i+1)*1024,title:`Legacy task ${i+1}`,column:legacy.columns[0].id,visible:i!==0}));legacy.tasks[0].column=legacy.columns[1].id;legacy.columns[1].name='SECRET INTERNAL COLUMN';legacy.columns[0].publicName='Client backlog';legacy.comments.push({id:randomUUID(),task:'',author:'Owner',content:'INTERNAL SECRET',audience:'internal',created:new Date().toISOString()});await db.doc(`accounts/${outsider.uid}`).set({plan:'free',revision:1,activeProjectId:legacy.id,notifications:[]});await db.doc(`accounts/${outsider.uid}/projects/${legacy.id}`).set(legacy);await call('migrateWorkspace',{},outsider);const migrated=await db.doc(`accounts/${outsider.uid}/projects/${legacy.id}`).get();assert.equal(migrated.data().schema,3);assert.ok(!('tasks' in migrated.data()));assert.equal((await migrated.ref.collection('tasks').get()).size,1001);assert.ok((await db.doc(`accounts/${outsider.uid}/migrationBackups/${legacy.id}`).get()).exists);assert.equal((await db.doc(`accounts/${outsider.uid}`).get()).data().schema,3);
const largeShare=await call('shareProject',{projectId:legacy.id,action:'rotate'},outsider);let after='',publicTasks=0;do{const r=await fetch(root+'clientPortal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:largeShare.url.split('#portal=')[1],session:'large',after})});const result=await r.json();assert.equal(r.status,200);assert.ok(!JSON.stringify(result).includes('SECRET'));assert.equal(result.columns[0].name,'Client backlog');publicTasks+=result.tasks.length;after=result.next;}while(after);assert.equal(publicTasks,1000);

// Independent task edits must not conflict, but stale updates to the same task do.
p={...(await ref.get()).data(),tasks:(await ref.collection('tasks').get()).docs.map(d=>d.data()),comments:[],suggestions:[]};
const left=structuredClone(p),right=structuredClone(p);left.tasks[0].title='Concurrent left';left.tasks[0].revision++;right.tasks[1].title='Concurrent right';right.tasks[1].revision++;
await Promise.all([call('projectCommand',{owner:owner.uid,projectId:p.id,requestId:randomUUID(),patch:projectPatch(p,left)},owner),call('projectCommand',{owner:owner.uid,projectId:p.id,requestId:randomUUID(),patch:projectPatch(p,right)},owner)]);
assert.equal((await ref.collection('tasks').doc(left.tasks[0].id).get()).data().title,'Concurrent left');assert.equal((await ref.collection('tasks').doc(right.tasks[1].id).get()).data().title,'Concurrent right');
await call('adminCommand',{action:'list'},owner,false);await call('exportProject',{owner:owner.uid,projectId:p.id},outsider,false);
// Only the Auth emulator accepts unsigned fixture claims. No real admin account
// or production credential is created or modified by this test.
const tokenParts=owner.token.split('.'),adminClaims=JSON.parse(Buffer.from(tokenParts[1],'base64url').toString());adminClaims.admin=true;adminClaims.firebase.sign_in_second_factor='phone';const administrator={...owner,token:[tokenParts[0],Buffer.from(JSON.stringify(adminClaims)).toString('base64url'),tokenParts[2]].join('.')};
await call('adminCommand',{action:'plan',uid:owner.uid,plan:'pro'},administrator);const extraProject=makeProject('Pro second');await call('projectCommand',{owner:owner.uid,projectId:extraProject.id,requestId:randomUUID(),patch:projectPatch(undefined,extraProject)},owner);await call('adminCommand',{action:'plan',uid:owner.uid,plan:'free'},administrator);assert.equal((await db.doc(`accounts/${owner.uid}/projects/${extraProject.id}`).get()).data().frozen,true);
const frozen={...(await db.doc(`accounts/${owner.uid}/projects/${extraProject.id}`).get()).data(),tasks:[],comments:[],suggestions:[]},frozenEdit={...frozen,name:'Blocked frozen edit'};await call('projectCommand',{owner:owner.uid,projectId:extraProject.id,requestId:randomUUID(),patch:projectPatch(frozen,frozenEdit)},owner,false);
await call('adminCommand',{action:'control',disabled:['invite']},administrator);await call('inviteMember',{projectId:p.id,email:'blocked@example.com'},owner,false);await call('adminCommand',{action:'control',disabled:[]},administrator);
const exportStart=await call('exportProject',{owner:outsider.uid,projectId:legacy.id},outsider);const exported={...exportStart.project,tasks:[],comments:[],suggestions:[]};for(const kind of ['tasks','comments','suggestions']){let after='';do{const page=await call('exportProject',{owner:outsider.uid,projectId:legacy.id,kind,after,revision:exportStart.revision},outsider);exported[kind].push(...page.items);after=page.next;}while(after);}assert.equal(exported.tasks.length,1001);assert.equal(exported.comments.length,1);
const restoreId=randomUUID(),json=JSON.stringify(exported),chunks=[];for(let i=0;i<json.length;i+=150000)chunks.push(json.slice(i,i+150000));for(let index=0;index<chunks.length;index++)await call('restoreProject',{restoreId,action:'upload',index,total:chunks.length,chunk:chunks[index]},outsider);const restored=await call('restoreProject',{restoreId,action:'finish'},outsider);assert.equal(restored.projectId,restoreId);assert.deepEqual(await call('restoreProject',{restoreId,action:'finish'},outsider),restored);const restoredRef=db.doc(`accounts/${outsider.uid}/projects/${restoreId}`);assert.equal((await restoredRef.get()).data().status,'archived');assert.equal((await restoredRef.collection('tasks').get()).size,1001);assert.equal((await migrated.ref.collection('tasks').get()).size,1001);assert.ok((await db.doc(`restoreAudit/${outsider.uid}_${restoreId}`).get()).exists);

// Worker tests use a fake sender: no external SMTP service or real email.
const email=db.doc('emailOutbox/worker-test');await email.set({uid:owner.uid,status:'pending',attempts:0});let sends=0;const send=async()=>{sends++;await new Promise(r=>setTimeout(r,80));};await Promise.all([processEmailItem(db,email,send,async()=>true),processEmailItem(db,email,send,async()=>true)]);assert.equal(sends,1);assert.equal((await email.get()).data().status,'sent');
await email.set({uid:owner.uid,status:'pending',attempts:0});await processEmailItem(db,email,async()=>{throw Error('SMTP connection lost after delivery started');},async()=>true);assert.equal((await email.get()).data().status,'uncertain');await processEmailItem(db,email,send,async()=>true);assert.equal(sends,1);
await email.set({uid:owner.uid,status:'pending',attempts:0});await processEmailItem(db,email,send,async()=>false);assert.equal((await email.get()).data().status,'suppressed');assert.equal(sends,1);
await email.set({uid:owner.uid,status:'processing',leaseUntil:new Date(0),deliveryStarted:true});await processEmailItem(db,email,send,async()=>true);assert.equal((await email.get()).data().status,'uncertain');assert.equal(sends,1);
console.log('Server integration passed: small writes, idempotency, stale edits, owner isolation, verified invitations, member permissions, public projection, guest spam, revocation and preserved migration.');
console.log('Extended checks passed: 1,001-task migration, public pagination, independent concurrent writes, full export/restore, original preservation, audit and no duplicate email delivery.');
export {owner,member,outsider,p,legacy,db,call,root};
