import {memo,useEffect,useMemo,useRef,useState,useCallback} from 'react';
import {Plus,X,Settings,Columns3,Users,CalendarDays,Bell,Eye,Check,ArrowLeft,ArrowRight,Trash2,Lock,MessageSquare,GripVertical,Undo2,Download,Share2,RotateCcw,LayoutList,Shield,Upload,Search,ExternalLink} from 'lucide-react';
import {DndContext,DragOverlay,PointerSensor,KeyboardSensor,useSensor,useSensors,useDroppable,closestCorners,pointerWithin,type DragEndEvent,type CollisionDetection} from '@dnd-kit/core';
import {useVirtualizer} from '@tanstack/react-virtual';
import {SortableContext,useSortable,sortableKeyboardCoordinates,verticalListSortingStrategy} from '@dnd-kit/sortable';
import {CSS} from '@dnd-kit/utilities';
import {acceptSuggestion,canActivate,canEditTask,changePlan,completion,deleteColumn,normalizeProject,progress,templateProject,uid,writable,type Store,type Project,type Task,type Column,type Priority,type Preferences} from './domain';
import {rankBetween,metadata} from './patches';
import {restoredProject,validateBackup,BACKUP_MAX_BYTES} from './backup';
import {exportProject,exportWorkspace,restoreCloud} from './backup-client';
import Modal from './Modal';
import {load,persist} from './storage';
import {command} from './normalized-repository';
import {PortalBoard} from './Portal';
import {measureAction,recordEvent} from './telemetry';

type View='board'|'team'|'sprints'|'suggestions'|'notifications'|'portfolio'|'trash';
export interface Remote {store:Store;change:(store:Store,base?:Store)=>Promise<void>;userId:string;userName:string;userEmail:string;verified:boolean;server:boolean;select:(owner:string,id:string)=>void;thread:(task:string)=>void;moreComments:()=>Promise<void>;moreTasks:()=>Promise<void>;verify:()=>Promise<void>;signOut:()=>Promise<void>}
const data=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form).entries()) as Record<string,string>;
function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
const TaskCard=memo(function TaskCard({task,editable,onOpen}:{task:Task;editable:boolean;onOpen:(id:string)=>void}){
 const drag=useSortable({id:task.id,disabled:!editable});
 return <article ref={drag.setNodeRef} className={`task ${drag.isDragging?'dragging':''}`} style={{transform:CSS.Transform.toString(drag.transform),transition:drag.transition}}>
  <div className="task-top"><span className="task-id">CF-{task.number}</span>{editable&&<button ref={drag.setActivatorNodeRef} className="drag-handle" title="Move task" aria-label={`Move ${task.title}`} {...drag.attributes} {...drag.listeners}><GripVertical size={16}/></button>}</div>
  <button className="task-open" onClick={()=>onOpen(task.id)}><h3>{task.title}</h3><div className="task-meta"><span className={'priority '+task.priority}>{task.priority}</span>{!task.visible&&<Eye size={14} aria-label="Hidden from client"/>}{task.deadline&&<time dateTime={task.deadline}>{task.deadline}</time>}</div></button>
 </article>;
});
function VirtualTasks({tasks,editTask,onOpen}:{tasks:Task[];editTask:(task:Task)=>boolean;onOpen:(id:string)=>void}){
 const scroll=useRef<HTMLDivElement>(null),getItemKey=useCallback((index:number)=>tasks[index].id,[tasks]);
 const virtual=useVirtualizer({count:tasks.length,getScrollElement:()=>scroll.current,estimateSize:()=>160,overscan:4,getItemKey});
 return <div ref={scroll} className="virtual-tasks" tabIndex={0} aria-label="Column tasks"><div style={{height:virtual.getTotalSize(),position:'relative'}}>{virtual.getVirtualItems().map(row=><div key={row.key} ref={virtual.measureElement} data-index={row.index} className="virtual-row" style={{position:'absolute',top:0,left:0,width:'100%',transform:`translateY(${row.start}px)`}}><TaskCard task={tasks[row.index]} editable={editTask(tasks[row.index])} onOpen={onOpen}/></div>)}</div></div>;
}
function BoardColumn({column,tasks,edit,editTask,onOpen,onSettings}:{column:Column;tasks:Task[];edit:boolean;editTask:(task:Task)=>boolean;onOpen:(id:string)=>void;onSettings:(id:string)=>void}){
 const drop=useDroppable({id:column.id});return <section ref={drop.setNodeRef} className={'column '+(drop.isOver?'drop-target':'')}><div className="column-head"><span className="dot" style={{background:column.color}}/><strong>{column.name}</strong><span className={column.limit&&tasks.length>column.limit?'count over-limit':'count'}>{tasks.length}{column.limit?`/${column.limit}`:''}</span>{edit&&<button onClick={()=>onSettings(column.id)} title="Column settings" aria-label={`Settings for ${column.name}`}><Settings size={15}/></button>}</div><SortableContext items={tasks.map(t=>t.id)} strategy={verticalListSortingStrategy}>{tasks.length>80?<VirtualTasks tasks={tasks} editTask={editTask} onOpen={onOpen}/>:tasks.map(t=><TaskCard key={t.id} task={t} editable={editTask(t)} onOpen={onOpen}/>)}</SortableContext>{!tasks.length&&<div className="empty">No tasks</div>}</section>;
}

export default function App({remote}:{remote?:Remote}={}){
 const [store,setLocalStore]=useState<Store>(()=>remote?.store||load()),[selected,setSelected]=useState(store.projects[0]?.id),[view,setView]=useState<View>('board'),[actor,setActor]=useState('owner'),[client,setClient]=useState(false),[modal,setModal]=useState(''),[taskId,setTaskId]=useState(''),[columnId,setColumnId]=useState(''),[message,setMessage]=useState(''),[sprintFilter,setSprintFilter]=useState('all'),[search,setSearch]=useState(''),[pending,setPending]=useState(0),[saveError,setSaveError]=useState(''),[shareUrl,setShareUrl]=useState(''),[actionBusy,setActionBusy]=useState(false),[undo,setUndo]=useState<{project:string;task:string;column:string;rank:number;revision:number}|null>(null),[draft,setDraft]=useState<Record<string,string>>({});
 const storeRef=useRef(store),queue=useRef(Promise.resolve()),pendingRef=useRef(0),incoming=useRef<Store|null>(null),generation=useRef(0),failed=useRef<{next:Store;base:Store}|null>(null);
 const [dragged,setDragged]=useState<Task|null>(null),openedTaskRevision=useRef<number|undefined>(undefined);
 const p=store.projects.find(p=>p.id===selected)||store.projects[0],projectActor=remote&&p?.ownerId?p.members.find(m=>m.uid===remote.userId)?.id||remote.userId:actor;
 const member=p?.members.find(m=>m.id===projectActor),owner=projectActor==='owner'&&!client,active=!!p&&writable(store,p),edit=owner&&active,collaborate=active&&(owner||!!member?.collaborating)&&!client;
 const task=p?.tasks.find(t=>t.id===taskId),col=p?.columns.find(c=>c.id===columnId);
 const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:7}}),useSensor(KeyboardSensor,{coordinateGetter:sortableKeyboardCoordinates}));
 useEffect(()=>{if(!remote)return;incoming.current=remote.store;if(!pendingRef.current){storeRef.current=remote.store;setLocalStore(remote.store);}},[remote?.store]);
 useEffect(()=>{if(p&&remote){remote.select(p.ownerId||remote.userId,p.ownerId?p.id.split(':').at(-1)!:p.id);}},[p?.id,p?.schema,p?.loaded,remote?.userId]);
 useEffect(()=>{if(!remote){try{persist(store);}catch{setMessage('Browser storage is unavailable.');}}},[store,!!remote]);
 useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),7000);return()=>clearTimeout(timer);},[message]);
 function setStore(next:Store,originalBase?:Store){const base=originalBase||storeRef.current;storeRef.current=next;setLocalStore(next);if(!remote)return;
  const sequence=generation.current;pendingRef.current++;setPending(pendingRef.current);setSaveError('');
  queue.current=queue.current.catch(()=>{}).then(async()=>{if(sequence!==generation.current)return;try{await remote.change(next,base);}catch(e){generation.current++;failed.current={next,base};const text=(e as Error).message;setSaveError(text);setMessage(text);const restore=incoming.current||base;storeRef.current=restore;setLocalStore(restore);}}).finally(()=>{pendingRef.current--;setPending(pendingRef.current);if(!pendingRef.current&&incoming.current){storeRef.current=incoming.current;setLocalStore(incoming.current);}});
 }
 function mutate(fn:(s:Store,p:Project)=>void){const base=storeRef.current,next=structuredClone(base),project=next.projects.find(x=>x.id===p.id)!;try{fn(next,project);if(remote?.server&&JSON.stringify(metadata(base.projects.find(x=>x.id===p.id)!))!==JSON.stringify(metadata(project)))project.revision=(project.revision||0)+1;setStore(next);}catch(e){setMessage((e as Error).message);}}
 function notify(s:Store,text:string,target=''){if(!remote?.server)s.notifications.unshift({id:uid(),text,read:false,projectId:p.id,taskId:target,created:new Date().toISOString()});}
 function report(error:unknown){setMessage(error instanceof Error?error.message:'Please try again.');}
 async function action(fn:()=>Promise<void>){setActionBusy(true);try{await fn();}catch(e){report(e);}finally{setActionBusy(false);}}
 async function exportData(workspace=false){if(pendingRef.current)throw Error('Wait for pending saves before exporting.');setMessage('Preparing complete backup...');const value=remote?.server?workspace?await exportWorkspace(storeRef.current,remote.userId):await exportProject(p,remote.userId):workspace?storeRef.current:p;download(workspace?'clientflow-workspace-backup.json':'clientflow-project.json',value);setMessage('Backup ready.');}
 async function restoreFile(file:File){if(file.size>BACKUP_MAX_BYTES)throw Error('File exceeds 20 MB.');const imported=JSON.parse(await file.text()),projects=imported.format==='clientflow-workspace'||imported.version===2&&Array.isArray(imported.projects)?imported.projects:[imported];if(!Array.isArray(projects)||!projects.length||projects.length>1000)throw Error('Invalid workspace backup.');projects.forEach(validateBackup);let completed=0;try{for(const source of projects){setMessage(`Restoring ${completed+1}/${projects.length}...`);if(remote){if(!remote.server)throw Error('Cloud restore requires the server-enabled workspace.');setSelected(await restoreCloud(source));}else{const restored=restoredProject(source);setStore({...storeRef.current,projects:[...storeRef.current.projects,restored]});setSelected(restored.id);}completed++;}}catch(e){throw Error(`${completed}/${projects.length} restored. ${e instanceof Error?e.message:'Restore failed.'}`);}setModal('');setMessage(`${completed} archived project(s) restored. Existing projects are unchanged.`);}
 function newProject(name:string,template='blank'){const project=templateProject(name,template);if(remote){project.members[0].name=remote.userName;project.members[0].email=remote.userEmail;project.members[0].uid=remote.userId;}return project;}
 function move(id:string,column:string,beforeId?:string){const current=storeRef.current.projects.find(x=>x.id===p.id)!,t=current.tasks.find(t=>t.id===id);if(!t||!canEditTask(storeRef.current,current,projectActor,t))return;const end=measureAction('move');const tasks=current.tasks.filter(t=>!t.deletedAt&&t.column===column&&t.id!==id).sort((a,b)=>(a.rank||0)-(b.rank||0));const index=beforeId?tasks.findIndex(t=>t.id===beforeId):tasks.length;const at=index<0?tasks.length:index;const rank=rankBetween(tasks[at-1]?.rank,tasks[at]?.rank);
  setUndo({project:p.id,task:id,column:t.column,rank:t.rank||1024,revision:t.revision+1});mutate((_,project)=>{const task=project.tasks.find(t=>t.id===id)!;task.column=column;task.rank=rank;task.revision++;});end();
  const c=p.columns.find(c=>c.id===column);if(c?.limit&&tasks.length+1>c.limit)setMessage('Work-in-progress limit exceeded.');
 }
 function onDrop(e:DragEndEvent){if(!e.over||e.active.id===e.over.id)return;const id=String(e.active.id),over=String(e.over.id),target=p.tasks.find(t=>t.id===over);move(id,target?.column||over,target?.id);}
 const collision:CollisionDetection=args=>{const candidates={...args,droppableContainers:args.droppableContainers.filter(item=>item.id!==args.active.id)},hits=pointerWithin(candidates),cards=hits.filter(hit=>p.tasks.some(t=>t.id===hit.id));return cards.length?cards:hits.length?hits:closestCorners(candidates);};
 function undoMove(){if(!undo)return;const current=storeRef.current.projects.find(x=>x.id===undo.project),t=current?.tasks.find(x=>x.id===undo.task);if(!t||t.revision!==undo.revision){setMessage('Task changed since that move.');setUndo(null);return;}mutate((_,p)=>{const task=p.tasks.find(t=>t.id===undo.task)!;task.column=undo.column;task.rank=undo.rank;task.revision++;});setUndo(null);}
 function openTask(id=''){const current=p.tasks.find(t=>t.id===id);openedTaskRevision.current=current?.revision;setTaskId(id);remote?.thread(id);try{const saved=JSON.parse(sessionStorage.getItem(`clientflow.draft.${p.id}.${id||'new'}`)||'{}');if(current&&saved._revision!==undefined&&Number(saved._revision)!==current.revision){setDraft({});setMessage('Task changed since your draft. The saved draft was not applied.');}else setDraft(saved);}catch{setDraft({});}setModal('task');}
 const openTaskRef=useRef(openTask);openTaskRef.current=openTask;const stableOpen=useRef((id:string)=>openTaskRef.current(id)).current;
 function saveDraft(form:HTMLFormElement){try{const values=data(form),checkbox=form.elements.namedItem('visible') as HTMLInputElement|null;if(checkbox)values.visible=checkbox.checked?'on':'off';if(openedTaskRevision.current!==undefined)values._revision=String(openedTaskRevision.current);sessionStorage.setItem(`clientflow.draft.${p.id}.${taskId||'new'}`,JSON.stringify(values));}catch{}}
 function clearDraft(){try{sessionStorage.removeItem(`clientflow.draft.${p.id}.${taskId||'new'}`);}catch{}setDraft({});}
 const grouped=useMemo(()=>{const map=new Map<string,Task[]>();for(const c of p?.columns||[])map.set(c.id,[]);for(const t of p?.tasks||[])if(!t.deletedAt&&(sprintFilter==='all'||t.sprint===sprintFilter)&&(!search||t.title.toLowerCase().includes(search.toLowerCase())))map.get(t.column)?.push(t);map.forEach(tasks=>tasks.sort((a,b)=>(a.rank||0)-(b.rank||0)));return map;},[p?.tasks,p?.columns,sprintFilter,search]);
 function fields(t?:Task,disabled=false,suggestion=false){const value=(key:string,fallback='')=>!suggestion&&draft[key]!==undefined?draft[key]:String((t as unknown as Record<string,unknown>)?.[key]??fallback);const statusOnly=!owner&&member?.role!=='editor'&&!suggestion;
  return <><label>Title<input name="title" defaultValue={value('title')} required maxLength={160} disabled={disabled||statusOnly}/></label><label>Description<textarea name="description" defaultValue={value('description')} rows={3} maxLength={8000} disabled={disabled||statusOnly}/></label><div className="fields"><label>Status<select name="column" defaultValue={value('column',p.columns[0].id)} disabled={disabled}>{p.columns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Priority<select name="priority" defaultValue={value('priority','Medium')} disabled={disabled||statusOnly}>{['Low','Medium','High','Urgent'].map(x=><option key={x}>{x}</option>)}</select></label><label>Deadline<input name="deadline" type="date" defaultValue={value('deadline')} disabled={disabled||statusOnly}/></label><label>Assignee<select name="assignee" defaultValue={value('assignee')} disabled={disabled||statusOnly}><option value="">Unassigned</option>{p.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Sprint<select name="sprint" defaultValue={value('sprint')} disabled={disabled||statusOnly}><option value="">No sprint</option>{p.sprints.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><label className="checkbox"><input name="visible" type="checkbox" defaultChecked={draft.visible!==undefined?draft.visible==='on':t?.visible??true} disabled={disabled||statusOnly}/>Visible to client</label></>;
 }
 function comments(target:string){return <><div className="comments">{p.comments.filter(c=>c.task===target&&!c.moderated).sort((a,b)=>a.created.localeCompare(b.created)).map(c=><div className="comment" key={c.id}><strong>{c.author}</strong><small>{c.guest?'Guest · unverified':c.audience==='client'?'Client reply':'Internal'}</small>{c.awaitingReply&&<span className="reply-badge">Awaiting reply</span>}<p>{c.content}</p><time>{new Date(c.created).toLocaleString('en',{timeZone:store.preferences?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone})}</time>{owner&&active&&<button title="Moderate comment" aria-label="Moderate comment" onClick={()=>mutate((_,p)=>{p.comments.find(x=>x.id===c.id)!.moderated=true;})}><Trash2 size={14}/></button>}</div>)}</div>{remote?.server&&<button onClick={()=>void action(remote.moreComments)}>Load earlier comments</button>}{collaborate&&<form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,d=data(f);if(!d.content.trim())return;mutate((s,p)=>{p.comments.push({id:uid(),task:target,author:member?.name||remote?.userName||'Project owner',content:d.content.trim(),audience:d.audience==='client'?'client':'internal',guest:false,created:new Date().toISOString()});notify(s,'New comment',target);});f.reset();}}><label>Conversation<select name="audience" defaultValue="internal"><option value="internal">Internal comment</option><option value="client" disabled={!!target&&!task?.visible}>Reply to client</option></select></label><label>Comment<textarea name="content" required maxLength={4000}/></label><div className="dialog-actions"><button className="primary">Post comment</button></div></form>}</>;}
 if(!p)return <div className="account-screen"><section className="account-panel"><a className="auth-brand" href="/">ClientFlow</a><h1>Your first project</h1><form onSubmit={e=>{e.preventDefault();const name=data(e.currentTarget).name.trim();if(name){const project=newProject(name,data(e.currentTarget).template);setStore({...store,projects:[project]});setSelected(project.id);recordEvent('project_created');}}}><label>Project name<input name="name" required maxLength={100} autoFocus/></label><TemplateSelect/><button className="primary auth-submit"><Plus size={17}/>Create project</button></form>{message&&<p role="alert">{message}</p>}{remote&&<button onClick={()=>void remote.signOut()}>Sign out</button>}</section></div>;
 if(client)return <><div className="preview-bar"><button onClick={()=>setClient(false)}><ArrowLeft size={16}/>Back to workspace</button><span>Client preview</span></div><PortalBoard project={p}/></>;
 const completed=completion(p),taskEditable=task&&canEditTask(store,p,projectActor,task),canCreate=edit||active&&member?.role==='editor';
 return <div className="app"><aside><a className="brand" href="/">ClientFlow<span className="mark">CF</span></a><div className="workspace">{remote?.userName||'Personal workspace'}<small>{store.plan==='pro'?'Pro':'Free'}</small></div><nav>{([['board',Columns3,'Board'],['team',Users,'Team'],['sprints',CalendarDays,'Sprints'],['suggestions',MessageSquare,'Suggestions'],['portfolio',LayoutList,'Projects'],['notifications',Bell,'Notifications'],['trash',Trash2,'Trash']] as const).map(([id,Icon,label])=><button key={id} className={view===id?'selected':''} onClick={()=>setView(id)}><Icon size={17}/>{label}{id==='notifications'&&store.notifications.some(n=>!n.read)&&<span className="badge">{store.notifications.filter(n=>!n.read).length}</span>}</button>)}</nav><footer>{!remote&&<button onClick={()=>setModal('demo')}>Demo controls</button>}<button onClick={()=>setModal('preferences')}><Settings size={16}/>Preferences</button>{remote&&<button onClick={()=>void action(remote.signOut)}>Sign out</button>}</footer></aside>
 <main><header><div className="project-picker"><select aria-label="Project" value={p.id} onChange={e=>{setSelected(e.target.value);setSprintFilter('all');setSearch('');setView('board');setShareUrl('');setUndo(null);}}>{store.projects.map(p=><option key={p.id} value={p.id}>{p.name}{p.ownerId?' · Shared':''}{p.frozen?' · Frozen':''}</option>)}</select><button title="New project" aria-label="New project" onClick={()=>{if(!canActivate(store)){recordEvent('free_slot_limit');setModal('plan');return;}setModal('new-project');}}><Plus size={17}/></button></div><div className="save-status" role="status">{saveError?<><span className="danger">Save failed</span><button disabled={pending>0} onClick={()=>{const value=failed.current;if(value){if(!remote?.server&&JSON.stringify(storeRef.current)!==JSON.stringify(value.base)){setMessage('Workspace changed. Reopen the task before saving again.');return;}failed.current=null;setStore(value.next,value.base);}}}>Retry</button><button onClick={()=>{failed.current=null;setSaveError('');}} title="Discard failed change" aria-label="Discard failed change"><X size={14}/></button></>:pending?`${pending} pending`:remote?'Saved':'Local demo'}</div><div className="actions"><button onClick={()=>setClient(true)} title="Client preview"><Eye size={17}/><span>Client preview</span></button>{owner&&<button onClick={()=>setModal('share')} title="Share project"><Share2 size={17}/><span>Share</span></button>}</div></header>
 <section className="project-head"><div><h1>{p.name}</h1>{p.description&&<p>{p.description}</p>}</div><div className="actions"><button onClick={()=>{remote?.thread('');setModal('project-comments');}} title="Project comments" aria-label="Project comments"><MessageSquare size={17}/></button><button disabled={actionBusy||pending>0} onClick={()=>void action(()=>exportData())} title="Export project" aria-label="Export project"><Download size={17}/></button>{owner&&<button onClick={()=>setModal('project')} title="Project settings" aria-label="Project settings"><Settings size={17}/></button>}</div></section>
 <section className="summary"><span>{p.frozen?'Frozen':p.status}</span><div className="progress"><div><span>Completed tasks</span><strong>{progress(p)}%</strong></div><progress max="100" value={progress(p)}/></div><span>{completed.done}/{completed.total} tasks</span><span>{p.members.filter(m=>m.collaborating).length} members</span>{!active&&<span className="read-only"><Lock size={14}/>Read-only</span>}{undo&&<button onClick={undoMove} title="Undo move" aria-label="Undo move"><Undo2 size={16}/></button>}</section>
 {remote&&!remote.verified&&<div className="verification-band"><span>Verify your email before inviting or sharing.</span><button disabled={actionBusy} onClick={()=>void action(async()=>{await remote.verify();setMessage('Verification email sent. Sign in again after verifying.');})}>Send verification email</button></div>}
{view==='board'&&<><div className="board-toolbar"><h2>Kanban board</h2><div className="actions"><label className="search"><Search size={16}/><input aria-label="Search tasks" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks"/></label><select aria-label="Sprint filter" value={sprintFilter} onChange={e=>setSprintFilter(e.target.value)}><option value="all">All tasks</option><option value="">Backlog</option>{p.sprints.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>{canCreate&&<button className="primary" onClick={()=>openTask()}><Plus size={17}/>New task</button>}{edit&&<button title="Add column" aria-label="Add column" onClick={()=>{setColumnId('');setModal('column');}}><Plus size={17}/></button>}</div></div>{p.loaded===false?<div className="content" role="status">Loading tasks...</div>:<DndContext sensors={sensors} collisionDetection={collision} onDragStart={e=>setDragged(p.tasks.find(t=>t.id===e.active.id)||null)} onDragCancel={()=>setDragged(null)} onDragEnd={e=>{setDragged(null);onDrop(e);}}><div className="board">{p.columns.map(c=><BoardColumn key={c.id} column={c} tasks={grouped.get(c.id)||[]} edit={edit} editTask={t=>canEditTask(store,p,projectActor,t)} onOpen={stableOpen} onSettings={id=>{setColumnId(id);setModal('column');}}/>)}</div><DragOverlay>{dragged&&<article className="task drag-overlay"><span className="task-id">CF-{dragged.number}</span><h3>{dragged.title}</h3></article>}</DragOverlay></DndContext>}{remote?.server&&p.tasks.length<(p.counts?.total||0)&&<button className="load-more" disabled={actionBusy} onClick={()=>void action(remote.moreTasks)}>Load more tasks</button>}</>}
 {view==='portfolio'&&<section className="content"><div className="section-title"><h2>Projects</h2><button title="Import project" aria-label="Import project" onClick={()=>setModal('import')}><Upload size={17}/></button></div><div className="project-table">{store.projects.map(project=><button key={project.id} onClick={()=>{setSelected(project.id);setView('board');}}><strong>{project.name}</strong><span>{project.frozen?'Frozen':project.status}</span><span>{completion(project).done}/{completion(project).total}</span><progress max="100" value={progress(project)}/></button>)}</div></section>}
 {view==='team'&&<section className="content"><div className="section-title"><h2>Team</h2>{edit&&<button className="primary" onClick={()=>setModal('member')}><Plus size={17}/>{remote?'Invite member':'Add member'}</button>}</div>{p.members.map(m=><div className="row" key={m.id}><span className="avatar">{m.name.slice(0,1)}</span><div><strong>{m.name}</strong><p>{m.email}</p></div><span>{m.id==='owner'?'Owner':m.role==='editor'?'Editor':'Member'}</span>{m.id!=='owner'&&edit&&<><label className="checkbox"><input type="checkbox" checked={m.collaborating} onChange={e=>{const checked=e.target.checked;if(checked&&store.plan==='free'&&p.members.filter(m=>m.collaborating).length>=5){setMessage('Free allows five collaborating members.');return;}mutate((_,p)=>{p.members.find(x=>x.id===m.id)!.collaborating=checked;});}}/>Collaborating</label><select aria-label={`Permissions for ${m.name}`} value={m.role==='editor'?'editor':m.ownStatus?'own':'member'} onChange={e=>mutate((_,p)=>{const member=p.members.find(x=>x.id===m.id)!;member.role=e.target.value==='editor'?'editor':'member';member.ownStatus=e.target.value==='own';})}><option value="member">Comment & suggest</option><option value="own">Assigned task status</option><option value="editor">Edit tasks</option></select>{remote?.server&&m.uid&&<button title="Remove member" aria-label={`Remove ${m.name}`} onClick={()=>void action(async()=>{await command('removeMember',{projectId:p.id,uid:m.uid});})}><Trash2 size={16}/></button>}</>}</div>)}</section>}
 {view==='sprints'&&<section className="content"><div className="section-title"><h2>Sprints</h2>{edit&&<button className="primary" onClick={()=>setModal('sprint')}><Plus size={17}/>New sprint</button>}</div>{p.sprints.map(s=><div className="row" key={s.id}><div><strong>{s.name}</strong><p>{s.start} – {s.end}</p></div><select aria-label={`Status of ${s.name}`} value={s.status} disabled={!edit} onChange={e=>mutate((_,p)=>{p.sprints.find(x=>x.id===s.id)!.status=e.target.value as typeof s.status;})}><option value="planned">Planned</option><option value="active">Active</option><option value="completed">Completed</option></select></div>)}{!p.sprints.length&&<div className="empty">No sprints</div>}</section>}
 {view==='suggestions'&&<section className="content"><div className="section-title"><h2>Suggested changes</h2>{edit&&p.suggestions.some(s=>s.status==='pending')&&<button onClick={()=>mutate((s,p)=>{const touched=new Set<string>();let count=0;for(const suggestion of p.suggestions.filter(x=>x.status==='pending')){const task=p.tasks.find(t=>t.id===suggestion.task);if(touched.has(suggestion.task)||!task||task.revision!==suggestion.revision)continue;acceptSuggestion(p,suggestion);touched.add(suggestion.task);count++;}notify(s,`${count} suggestions accepted`);setMessage(`${count} accepted. Conflicting suggestions were left pending.`);})}><Check size={16}/>Accept independent changes</button>}</div>{p.suggestions.map(s=><article className="suggestion" key={s.id}><strong>{p.tasks.find(t=>t.id===s.task)?.title||'Task'}</strong><p>{s.author} · {s.status}</p><dl>{Object.entries(s.changes).map(([key,value])=><div key={key}><dt>{key}</dt><dd><del>{String((p.tasks.find(t=>t.id===s.task) as unknown as Record<string,unknown>)?.[key]??'')}</del><span>{key==='column'?p.columns.find(c=>c.id===value)?.name:String(value)}</span></dd></div>)}</dl><p>{s.reason}</p>{edit&&s.status==='pending'&&<div className="actions"><button onClick={()=>mutate((store,p)=>{acceptSuggestion(p,p.suggestions.find(x=>x.id===s.id)!);notify(store,'Suggestion accepted',s.task);})}><Check size={16}/>Accept</button><button onClick={()=>mutate((store,p)=>{p.suggestions.find(x=>x.id===s.id)!.status='rejected';notify(store,'Suggestion rejected',s.task);})}><X size={16}/>Reject</button></div>}</article>)}{!p.suggestions.length&&<div className="empty">No suggestions</div>}</section>}
 {view==='notifications'&&<section className="content"><h2>Notifications</h2>{store.notifications.map(n=><div className={'row '+(!n.read?'unread':'')} key={n.id}><div><strong>{n.text}</strong>{n.created&&<p>{new Date(n.created).toLocaleString()}</p>}</div><button title="Open notification" aria-label="Open notification" onClick={()=>{if(n.projectId&&store.projects.some(p=>p.id===n.projectId)){setSelected(n.projectId);setTaskId(n.taskId||'');remote?.thread(n.taskId||'');setModal(n.taskId?'task':'project-comments');}setStore({...store,notifications:store.notifications.map(x=>x.id===n.id?{...x,read:true}:x)});}}><ExternalLink size={16}/></button></div>)}{!store.notifications.length&&<div className="empty">No notifications</div>}</section>}
 {view==='trash'&&<section className="content"><h2>Deleted tasks</h2>{p.tasks.filter(t=>t.deletedAt).map(t=><div className="row" key={t.id}><div><strong>{t.title}</strong><p>CF-{t.number}</p></div>{edit&&<button title="Restore task" aria-label={`Restore ${t.title}`} onClick={()=>mutate((_,p)=>{const task=p.tasks.find(x=>x.id===t.id)!;delete task.deletedAt;if(!p.columns.some(c=>c.id===task.column))task.column=p.columns[0].id;task.revision++;})}><RotateCcw size={16}/></button>}</div>)}</section>}
 {modal==='task'&&<Modal title={task?`CF-${task.number}`:'New task'} close={()=>setModal('')}><form onChange={e=>saveDraft(e.currentTarget)} onSubmit={e=>{e.preventDefault();if(!(task?taskEditable:canCreate))return;if(task&&task.revision!==openedTaskRevision.current){setMessage('Task changed while editing. Close and reopen it before saving.');return;}const d=data(e.currentTarget);mutate((s,p)=>{const t=p.tasks.find(x=>x.id===taskId);if(t&&!owner&&member?.role!=='editor'){t.column=d.column;t.revision++;}else{const f={title:d.title.trim(),description:d.description,column:d.column,priority:d.priority as Priority,deadline:d.deadline,assignee:d.assignee,visible:d.visible==='on',sprint:d.sprint};if(!f.title)throw Error('Title is required.');if(t){Object.assign(t,f);t.revision++;}else{p.taskSequence=Math.max(p.taskSequence||0,...p.tasks.map(t=>t.number||0))+1;p.tasks.push({id:uid(),number:p.taskSequence,rank:Math.max(0,...p.tasks.filter(t=>t.column===f.column).map(t=>t.rank||0))+1024,revision:0,...f});recordEvent('task_created');}}notify(s,'Task updated',taskId);});clearDraft();setModal('');}}>{fields(task,task?!taskEditable:!canCreate)}{(task?taskEditable:canCreate)&&<div className="dialog-actions">{task&&owner&&<button type="button" title="Delete task" aria-label="Delete task" className="danger" onClick={()=>{if(task.revision!==openedTaskRevision.current){setMessage('Task changed while editing. Close and reopen it first.');return;}mutate((_,p)=>{const t=p.tasks.find(t=>t.id===taskId)!;t.deletedAt=new Date().toISOString();t.revision++;});setModal('');setMessage('Task moved to Trash.');}}><Trash2 size={16}/></button>}<button className="primary">Save task</button></div>}</form>{task&&collaborate&&!owner&&<button className="suggest-button" onClick={()=>setModal('suggest')}>Suggest change</button>}{task&&<><h2 className="thread-title">Comments</h2>{comments(taskId)}</>}</Modal>}
 {modal==='suggest'&&task&&<Modal title="Suggest change" close={()=>setModal('')}><form onSubmit={e=>{e.preventDefault();if(!collaborate)return;const d=data(e.currentTarget),changes:Partial<Task>={};for(const key of ['title','description','column','priority','deadline','assignee','sprint'] as const)if(d[key]!==task[key])(changes as Record<string,string>)[key]=d[key];if(!Object.keys(changes).length){setMessage('Change at least one field.');return;}mutate((s,p)=>{p.suggestions.push({id:uid(),task:task.id,author:member?.name||'Member',changes,reason:d.reason,revision:task.revision,status:'pending'});notify(s,'New change suggestion',task.id);});setModal('');}}>{fields(task,false,true)}<label>Reason<textarea name="reason" maxLength={2000}/></label><div className="dialog-actions"><button className="primary">Submit suggestion</button></div></form></Modal>}
 {modal==='column'&&<Modal title={col?'Edit column':'New column'} close={()=>setModal('')}><form onSubmit={e=>{e.preventDefault();if(!edit)return;const d=data(e.currentTarget);mutate((_,p)=>{const f={name:d.name.trim(),publicName:d.publicName.trim(),color:d.color,done:d.done==='on',limit:Number(d.limit)};if(!f.name)throw Error('Column name is required.');if(col)Object.assign(p.columns.find(c=>c.id===col.id)!,f);else p.columns.push({id:uid(),...f});});setModal('');}}><label>Name<input name="name" defaultValue={col?.name} required maxLength={60}/></label><label>Client-facing name<input name="publicName" defaultValue={col?.publicName} maxLength={60}/></label><div className="fields"><label>Color<input name="color" type="color" defaultValue={col?.color||'#698b83'}/></label><label>WIP limit<input name="limit" type="number" min="0" max="999" defaultValue={col?.limit||0}/></label></div><label className="checkbox"><input name="done" type="checkbox" defaultChecked={col?.done}/>Completed column</label>{col&&<div className="actions reorder"><button type="button" title="Move left" disabled={p.columns.indexOf(col)===0} onClick={()=>mutate((_,p)=>{const i=p.columns.findIndex(c=>c.id===col.id);[p.columns[i-1],p.columns[i]]=[p.columns[i],p.columns[i-1]];})}><ArrowLeft size={16}/></button><button type="button" title="Move right" disabled={p.columns.indexOf(col)===p.columns.length-1} onClick={()=>mutate((_,p)=>{const i=p.columns.findIndex(c=>c.id===col.id);[p.columns[i+1],p.columns[i]]=[p.columns[i],p.columns[i+1]];})}><ArrowRight size={16}/></button></div>}<div className="dialog-actions">{col&&<button type="button" className="danger" disabled={p.columns.length===1} onClick={()=>setModal('delete-column')}><Trash2 size={16}/>Delete</button>}<button className="primary">Save column</button></div></form></Modal>}
 {modal==='delete-column'&&col&&<Modal title="Delete column" close={()=>setModal('')}><form onSubmit={e=>{e.preventDefault();mutate((_,p)=>deleteColumn(p,col.id,data(e.currentTarget).destination));setModal('');}}><label>Move tasks to<select name="destination">{p.columns.filter(c=>c.id!==col.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="dialog-actions"><button className="danger">Delete column</button></div></form></Modal>}
 {(modal==='new-project'||modal==='project')&&<Modal title={modal==='new-project'?'New project':'Project settings'} close={()=>setModal('')}><form onSubmit={e=>{e.preventDefault();if(!owner)return;const d=data(e.currentTarget);if(modal==='new-project'){if(!canActivate(store))return;const next=newProject(d.name.trim(),d.template);setStore({...store,projects:[...store.projects,next]});setSelected(next.id);recordEvent('project_created');}else{if(d.status==='active'&&!canActivate(store,p.id)){setMessage('Free allows one active project.');return;}if(p.frozen&&store.plan==='free'){setMessage('This project remains frozen until Pro is restored.');return;}mutate((_,p)=>{if(active){p.name=d.name.trim();p.description=d.description;p.guestComments=d.guestComments==='on';if(store.plan==='pro'&&d.brandName)p.branding={name:d.brandName.trim(),color:d.brandColor};}p.status=d.status as Project['status'];});}setModal('');}}><label>Name<input name="name" defaultValue={modal==='project'?p.name:''} required maxLength={100} disabled={modal==='project'&&!active}/></label>{modal==='new-project'?<TemplateSelect/>:<><label>Description<textarea name="description" defaultValue={p.description} disabled={!active} maxLength={8000}/></label><label>Status<select name="status" defaultValue={p.status} disabled={!!p.frozen&&store.plan==='free'}><option value="active">Active</option><option value="completed">Completed</option><option value="archived">Archived</option></select></label><label className="checkbox"><input type="checkbox" name="guestComments" defaultChecked={p.guestComments} disabled={!active}/>Allow client comments</label>{store.plan==='pro'&&<div className="fields"><label>Brand name<input name="brandName" defaultValue={p.branding?.name} maxLength={80}/></label><label>Brand color<input name="brandColor" type="color" defaultValue={p.branding?.color||'#187552'}/></label></div>}</>}<div className="dialog-actions"><button className="primary">Save project</button></div></form></Modal>}
 {modal==='member'&&<Modal title={remote?'Invite member':'Add demo member'} close={()=>setModal('')}><form onSubmit={e=>{e.preventDefault();const d=data(e.currentTarget);if(remote){if(!remote.server){setMessage('Secure invitations require the server deployment.');return;}void action(async()=>{const result=await command<{url:string}>('inviteMember',{projectId:p.id,email:d.email});setShareUrl(result.url);setMessage('Invitation created; email is queued.');});return;}if(store.plan==='free'&&p.members.filter(m=>m.collaborating).length>=5){setMessage('Free allows five collaborating members.');return;}if(p.members.some(m=>m.email.toLowerCase()===d.email.toLowerCase())){setMessage('Already a member.');return;}mutate((_,p)=>p.members.push({id:uid(),name:d.name.trim(),email:d.email,collaborating:true,role:'member'}));setModal('');}}>{!remote&&<label>Name<input name="name" required maxLength={80}/></label>}<label>Email<input name="email" type="email" required/></label>{shareUrl&&<label>Invitation link<input readOnly value={shareUrl}/></label>}<div className="dialog-actions"><button className="primary" disabled={actionBusy}>{remote?'Create invitation':'Add member'}</button></div></form></Modal>}
 {modal==='sprint'&&<Modal title="New sprint" close={()=>setModal('')}><form onSubmit={e=>{e.preventDefault();const d=data(e.currentTarget);if(d.end<d.start){setMessage('End date must follow start date.');return;}mutate((_,p)=>p.sprints.push({id:uid(),name:d.name.trim(),start:d.start,end:d.end,status:'planned'}));setModal('');}}><label>Name<input name="name" required maxLength={80}/></label><div className="fields"><label>Start<input name="start" type="date" required/></label><label>End<input name="end" type="date" required/></label></div><div className="dialog-actions"><button className="primary">Create sprint</button></div></form></Modal>}
 {modal==='project-comments'&&<Modal title="Project comments" close={()=>setModal('')}>{comments('')}</Modal>}
 {modal==='share'&&<Modal title="Client link" close={()=>setModal('')}><label>Link<input readOnly value={shareUrl}/></label><div className="dialog-actions"><button disabled={actionBusy||!remote?.server} onClick={()=>void action(async()=>{const r=await command<{url:string}>('shareProject',{projectId:p.id,action:'rotate'});setShareUrl(r.url);recordEvent('portal_shared');})}><Share2 size={16}/>Create / rotate</button><button disabled={actionBusy||!remote?.server} className="danger" onClick={()=>void action(async()=>{await command('shareProject',{projectId:p.id,action:'revoke'});setShareUrl('');setMessage('Client link revoked.');})}><Lock size={16}/>Revoke</button></div>{!remote?.server&&<p className="availability">Public sharing awaits secure server deployment.</p>}</Modal>}
 {modal==='preferences'&&<Modal title="Preferences" close={()=>setModal('')}><form onSubmit={e=>{e.preventDefault();const d=data(e.currentTarget),preferences:Preferences={timezone:d.timezone,email:d.email==='on',digest:d.digest as Preferences['digest'],mutedProjects:d.muted==='on'?[...new Set([...(store.preferences?.mutedProjects||[]),p.id])]:store.preferences?.mutedProjects.filter(x=>x!==p.id)||[]};try{new Intl.DateTimeFormat('en',{timeZone:preferences.timezone});}catch{setMessage('Enter a valid timezone.');return;}setStore({...store,preferences});setModal('');}}><label>Timezone<input name="timezone" defaultValue={store.preferences?.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone} required/></label><label className="checkbox"><input name="email" type="checkbox" defaultChecked={store.preferences?.email??true}/>Email notifications</label><label>Activity digest<select name="digest" defaultValue={store.preferences?.digest||'daily'}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="off">Off</option></select></label><label className="checkbox"><input name="muted" type="checkbox" defaultChecked={store.preferences?.mutedProjects.includes(p.id)}/>Mute this project</label><div className="dialog-actions"><button className="primary">Save preferences</button><button type="button" disabled={actionBusy||pending>0} onClick={()=>void action(()=>exportData(true))} title="Export workspace"><Download size={16}/></button></div></form>{remote?.server&&<button className="danger" onClick={()=>{if(confirm('Request account deletion? Your data will remain until the request is processed.'))void action(async()=>{await command('accountCommand',{action:'deleteRequest'});setMessage('Deletion request recorded.');});}}>Request account deletion</button>}</Modal>}
 {modal==='import'&&<Modal title="Restore backup" close={()=>setModal('')}><label>Backup JSON<input type="file" accept="application/json" disabled={actionBusy} onChange={e=>{const file=e.target.files?.[0];if(file)void action(()=>restoreFile(file));}}/></label></Modal>}
 {modal==='demo'&&<Modal title="Local demo controls" close={()=>setModal('')}><label>Preview as<select value={actor} onChange={e=>{setActor(e.target.value);setView('board');}}>{p.members.map(m=><option key={m.id} value={m.id}>{m.name} ({m.id==='owner'?'Owner':m.collaborating?'Member':'Read-only'})</option>)}</select></label><label>Owner plan<select value={store.plan} onChange={e=>setStore(changePlan(store,e.target.value as Store['plan']))}><option value="free">Free</option><option value="pro">Pro (simulated)</option></select></label></Modal>}
 {modal==='plan'&&<Modal title="Project limit" close={()=>setModal('')}><p>Free includes one active project and five collaborating members. Complete or archive the current project to create another.</p><div className="dialog-actions"><button onClick={()=>setModal('project')}>Project settings</button><button onClick={()=>setModal('')}>Close</button></div></Modal>}
 {message&&<div id="notice" style={{display:'block'}} role="status">{message}</div>}
 </main></div>;
}
function TemplateSelect(){return <label>Template<select name="template" defaultValue="blank"><option value="blank">Blank project</option><option value="website">Website</option><option value="marketing">Marketing campaign</option><option value="design">Design project</option></select></label>;}
