export type Status = 'active' | 'completed' | 'archived';
export type Priority = 'Low' | 'Medium' | 'High' | 'Urgent';
export interface Column { id:string; name:string; color:string; done:boolean; limit:number; publicName?:string }
export interface Member { id:string; name:string; email:string; collaborating:boolean; uid?:string; role?:'member'|'editor'; ownStatus?:boolean }
export interface Task { id:string; title:string; description:string; column:string; priority:Priority; deadline:string; assignee:string; visible:boolean; sprint:string; revision:number; number?:number; rank?:number; deletedAt?:string }
export interface Sprint { id:string; name:string; start:string; end:string; status:'planned'|'active'|'completed' }
export interface Comment { id:string; task:string; author:string; content:string; audience:'internal'|'client'; created:string; guest?:boolean; awaitingReply?:boolean; moderated?:boolean }
export interface Suggestion { id:string; task:string; author:string; changes:Partial<Task>; reason:string; revision:number; status:'pending'|'accepted'|'rejected' }
export interface Project { id:string; name:string; description:string; status:Status; created:number; columns:Column[]; tasks:Task[]; members:Member[]; sprints:Sprint[]; comments:Comment[]; suggestions:Suggestion[]; guestComments:boolean; frozen?:boolean; ownerId?:string; revision?:number; taskSequence?:number; branding?:{name:string;color:string}; loaded?:boolean; counts?:{total:number;done:number;publicTotal:number;publicDone:number}; publicColumnCounts?:Record<string,number>; schema?:number }
export interface Notification { id:string; text:string; read:boolean; projectId?:string; taskId?:string; created?:string }
export interface Preferences { timezone:string; email:boolean; digest:'daily'|'weekly'|'off'; mutedProjects:string[] }
export interface Store { version:2; plan:'free'|'pro'; projects:Project[]; notifications:Notification[]; preferences?:Preferences }
export const uid=()=>crypto.randomUUID();
export function makeProject(name:string):Project {return {id:uid(),name,description:'',status:'active',created:Date.now(),columns:['Backlog','To Do','In Progress','Review','Done'].map((name,i)=>({id:uid(),name,color:['#8b939a','#507ac4','#c39134','#ad6896','#258560'][i],done:i===4,limit:0})),tasks:[],members:[{id:'owner',name:'Project owner',email:'',collaborating:true}],sprints:[],comments:[],suggestions:[],guestComments:true};}
export function activeProject(store:Store):string|undefined{return [...store.projects].filter(p=>p.status==='active'&&!p.frozen).sort((a,b)=>a.created-b.created||a.id.localeCompare(b.id))[0]?.id;}
export function writable(store:Store,p:Project):boolean{return p.status==='active'&&(p.ownerId?!p.frozen:store.plan==='pro'||!p.frozen&&activeProject({...store,projects:store.projects.filter(x=>!x.ownerId)})===p.id);}
export function canActivate(store:Store,id?:string):boolean{return store.plan==='pro'||!store.projects.some(p=>!p.ownerId&&p.status==='active'&&!p.frozen&&p.id!==id);}
export function completion(p:Project,client=false):{done:number;total:number} {if(p.schema===3&&p.counts||p.loaded===false&&p.counts)return {done:client?p.counts!.publicDone:p.counts!.done,total:client?p.counts!.publicTotal:p.counts!.total};const tasks=p.tasks.filter(t=>!t.deletedAt&&(!client||t.visible));const done=new Set(p.columns.filter(c=>c.done).map(c=>c.id));return {done:tasks.filter(t=>done.has(t.column)).length,total:tasks.length};}
export function progress(p:Project,client=false):number {const {done,total}=completion(p,client);return total?Math.round(done/total*100):0;}
export function canEditTask(store:Store,p:Project,actor:string,task?:Task):boolean {if(!writable(store,p))return false;const m=p.members.find(m=>m.id===actor);return actor==='owner'||!!m?.collaborating&&(m.role==='editor'||!!task&&!!m.ownStatus&&task.assignee===actor);}
export function normalizeProject(p:Project):Project {const value=structuredClone(p);value.tasks.forEach((t,i)=>{t.number??=i+1;t.rank??=(i+1)*1024;});value.taskSequence=Math.max(value.taskSequence||0,...value.tasks.map(t=>t.number||0));return value;}
export function changePlan(store:Store,plan:Store['plan']):Store {const next=structuredClone(store);if(next.plan===plan)return next;next.plan=plan;if(plan==='free'){const projects=next.projects.filter(p=>p.status==='active').sort((a,b)=>a.created-b.created||a.id.localeCompare(b.id));projects.forEach((p,i)=>{p.frozen=i>0;let count=0;p.members.forEach(m=>{if(m.id==='owner')m.collaborating=true;else if(m.collaborating)m.collaborating=++count<=4;});});}else next.projects.forEach(p=>p.frozen=false);return next;}
export function publicProject(p:Project) {const tasks=p.tasks.filter(t=>t.visible&&!t.deletedAt);return {id:p.id,name:p.name,status:p.status,guestComments:p.guestComments,counts:completion(p,true),columns:p.columns.filter(c=>tasks.some(t=>t.column===c.id)).map(c=>({id:c.id,name:c.publicName||c.name,color:c.color,done:c.done})),tasks:tasks.map(t=>({id:t.id,title:t.title,column:t.column,number:t.number,rank:t.rank})),comments:p.comments.filter(c=>c.audience==='client'&&!c.moderated&&(!c.task||tasks.some(t=>t.id===c.task))).map(c=>({id:c.id,task:c.task,author:c.author,content:c.content,created:c.created,guest:!!c.guest}))};}
export function templateProject(name:string,template:string):Project {const p=makeProject(name);const titles:Record<string,string[]>={website:['Define scope','Design key pages','Build and review','Launch'],marketing:['Agree campaign goals','Create campaign assets','Review and approve','Publish campaign'],design:['Collect requirements','Explore concepts','Refine selected direction','Deliver final files']};p.tasks=(titles[template]||[]).map((title,i)=>({id:uid(),number:i+1,rank:(i+1)*1024,title,description:'',column:p.columns[0].id,priority:'Medium',deadline:'',assignee:'',visible:true,sprint:'',revision:0}));p.taskSequence=p.tasks.length;return p;}
export function deleteColumn(p:Project,id:string,destination:string):void {if(p.columns.length<2)throw Error('Keep at least one column.');if(p.tasks.some(t=>t.column===id)&&!p.columns.some(c=>c.id===destination&&c.id!==id))throw Error('Choose a destination column.');p.tasks.forEach(t=>{if(t.column===id){t.column=destination;t.revision++;}});p.columns=p.columns.filter(c=>c.id!==id);}
export function acceptSuggestion(p:Project,s:Suggestion):void {const task=p.tasks.find(t=>t.id===s.task);if(!task||task.revision!==s.revision)throw Error('Task changed since this suggestion. Reject it and request an updated suggestion.');Object.assign(task,s.changes);task.revision++;s.status='accepted';}
export function seed():Store {const p=makeProject('Website launch');p.description='From first ideas to a confident launch.';p.members.push({id:'member',name:'Alex Morgan',email:'alex@example.com',collaborating:true});['Define project scope','Design the homepage','Review content structure','Build responsive layouts','Launch checklist'].forEach((title,i)=>p.tasks.push({id:uid(),title,description:i===2?'Internal planning notes.':'',column:p.columns[[4,2,3,1,0][i]].id,priority:i<2?'High':'Medium',deadline:'',assignee:i<2?'owner':'member',visible:i!==2,sprint:'',revision:0}));return {version:2,plan:'free',projects:[p],notifications:[]};}
