import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,RefreshCw,MessageSquare} from 'lucide-react';
import {publicProject,type Project} from './domain';
import {portalEndpoint} from './firebase';
import Modal from './Modal';
type PublicProject=ReturnType<typeof publicProject>&{branding?:{name:string;color:string}};
interface Response extends PublicProject {next?:string|null}
export function PortalBoard({project,value,onThread}:{project?:Project;value?:Response;onThread?:(id:string)=>void}){
 const data:PublicProject|null=value||(project?publicProject(project):null);if(!data)return null;const {done,total}=data.counts;
 return <main className="portal"><header><strong>{data.branding?.name||'ClientFlow'}</strong><span>{data.status}</span></header><section className="project-head"><div><h1>{data.name}</h1></div><button title="Project comments" aria-label="Project comments" onClick={()=>onThread?.('')}><MessageSquare size={18}/></button></section><section className="summary"><div className="progress"><div><span>Completed tasks</span><strong>{total?Math.round(done/total*100):0}%</strong></div><progress max="100" value={total?done/total*100:0}/></div><span>{done}/{total} tasks</span></section><div className="board portal-board">{data.columns.filter(c=>data.tasks.some(t=>t.column===c.id)).map(c=><section className="column" key={c.id}><div className="column-head"><span className="dot" style={{background:c.color}}/><strong>{c.name}</strong><span>{data.tasks.filter(t=>t.column===c.id).length}</span></div>{data.tasks.filter(t=>t.column===c.id).sort((a,b)=>(a.rank||0)-(b.rank||0)).map(t=><button className="task" key={t.id} onClick={()=>onThread?.(t.id)}><span className="task-id">CF-{t.number}</span><h3>{t.title}</h3></button>)}</section>)}</div></main>;
}
export default function Portal({token}:{token:string}){
 const [value,setValue]=useState<Response|null>(null),[error,setError]=useState(''),[thread,setThread]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const session=useRef(crypto.randomUUID()),request=useRef(0),pages=useRef(1);
 async function api(body:Record<string,unknown>={}){const response=await fetch(portalEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,session:session.current,...body})});const value=await response.json();if(!response.ok)throw Error(value.error||'Link unavailable.');return value;}
 async function refresh(append=false){const current=++request.current;try{const result=await api({task:thread||'',...(append&&value?.next?{after:value.next}:{})});if(!append){let next=result.next;for(let i=1;i<pages.current&&next;i++){const page=await api({task:thread||'',after:next});result.tasks.push(...page.tasks);next=page.next;}result.next=next;}if(current!==request.current)return;if(append)pages.current++;setValue(previous=>append&&previous?{...result,tasks:[...previous.tasks,...result.tasks]}:result);setError('');}catch(e){if(current!==request.current)return;setError((e as Error).message);setValue(null);}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),30000);return()=>{clearInterval(timer);request.current++;};},[token,thread]);
 if(error)return <div className="account-screen"><section className="account-panel"><h1>Client link unavailable</h1><p role="alert">{error}</p><button onClick={()=>void refresh()}><RefreshCw size={16}/>Retry</button></section></div>;
 if(!value)return <div className="account-screen" role="status">Loading project...</div>;
 return <><PortalBoard value={value} onThread={id=>{setNotice('');setThread(id);}}/>{value.next&&<button className="load-more" onClick={()=>void refresh(true)}>Load more tasks</button>}{thread!==null&&<Modal title={thread?value.tasks.find(t=>t.id===thread)?.title||'Task comments':'Project comments'} close={()=>setThread(null)}>{value.comments.map(c=><div className="comment" key={c.id}><strong>{c.author}</strong><small>{c.guest?'Guest · unverified':'Team'}</small><p>{c.content}</p></div>)}{value.guestComments&&value.status==='active'&&<form onSubmit={async e=>{e.preventDefault();if(busy)return;const form=e.currentTarget,data=new FormData(form);setBusy(true);try{await api({action:'comment',task:thread,name:String(data.get('name')),content:String(data.get('content')),requestId:crypto.randomUUID()});form.reset();setNotice('Comment posted.');await refresh();}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}><label>Your name<input name="name" required maxLength={80}/></label><label>Comment<textarea name="content" required maxLength={4000}/></label><div className="dialog-actions"><button className="primary" disabled={busy}>{busy?'Posting...':'Post comment'}</button></div></form>}{notice&&<p role="status">{notice}</p>}</Modal>}</>;
}
